### ISSUE TITLE
Reponses to client

### ISSUE THREAD

**Issue by system205** [system205/BankSystem#8]
### Return good formatted HTTP 1.1 responses for: 

- [x] Return 401 unauthorized when /login with wrong credentials
- [x] Implement the 400 Bad request response.
- [x] 201 Created when /register is successful
- [x] 409 Conflict (in general) response. 

---

### Avoid all exceptions on the Server: 

- [x] Add **specific exceptions** when JSON is _malformed_ (no expected fields or other mistakes when parsing). Handle this exception as HTTP **Response 400** Bad Request. 
- [x] A _global exception handler process_ should be implemented (probably). All unknown exceptions should be handled as 500 Internal Error response.
---
- [x] Check that the user with the **email (unique** for customers) exists. Then **409 Conflict**  response.
- [x] Handle login when customer does not exist (password can't be found)
- [x] Check if the account has **not enough** money when transferring. **400 Bad request** (not enough money on account) response
- [x] Check that account when checking or transferring exists or is owned by the customer. 400 Bad request with a message in json otherwise.
- [x] Check that receiver's account exists when transferring money from sender. Bad Request with message should be returned
- [x] Validate registering data - email, name, surname, password must be not empty
- [x]  Check existence of user and his account when saving a new account to a user. If account exists it's ok, nothing to update in db.
- [x] A user should not have more than 5 accounts (active flag in a database). 409 response thrown.
---
- [x] Handle **JWT exception** (expiration). 401 with a message in the JSON body telling about it.

**Everything should be logged properly**
_(this issue will be expanded)_

**Comment by system205** [comment]
Logging should be also provided.

**Comment by Elham-EN** [comment]
Ok, you got someone already on the task

**Comment by system205** [comment]
> Ok, you got someone already on the task

Hi. How did you find this issue?) You can contribute though. But we try to follow best OOP (true) approaches (hide data and exposing only behaviour, not getters or setters)

**Comment by Banji0x** [comment]
Someone is on it already
